version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: "postgres:latest"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      PGDATA: /data/postgres
    volumes:
       - ./postgres:/data/postgres
    ports:
       - "127.0.0.1:${DB_PORT}:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge   
